import assets from "./assets";

const NFTData = [
  {
    id: "NFT-01",
    name: "Budi Wijaya",
    creator: "Tangerang, Banten",
    people: assets.petani,
    role: 'Farmer',
    price: '4.25',
    description:
      "Born and raised in a small vilage located in Tangerang,Banten. Mr.Budi have been a farmer all his life, driven by the desire to get a higher income in order to support his family. Mr Budi decided it's time to change. Click the visit button to know more about Mr.Budi and his business ",
    image: assets.petani_tua,
    img1: assets.farmer1,
    img2: assets.farmer2,
    trip: [
      {
        id: "1",
        place: "Tangerang",
        subplace: "Banten",
        date: "Sep 1-3",
        long: " | 3 days",
        Type: "Business",
        image: assets.sawah1,
      },
      {
        id: "2",
        place: "Tangerang",
        subplace: "Banten",
        date: "Sep 15-17",
        long: " | 3 days",
        Type: "Business",
        image: assets.sawah2,
      },
      {
        id: "3",
        place: "Tangerang",
        subplace: "Banten",
        date: "Sep 22-24",
        long: " | 3 days",
        Type: "Business",
        image: assets.sawah3,
      },
    ],
  },
  {
    id: "NFT-02",
    name: "Siti Nurbaya",
    creator: "Kuta, Bali",
    people: assets.dancer_close,
    role: 'Dancer',
    price: 7.25,
    description:
      "Balinese dance culture incorporates ancient Hindu traditions with drama that tell stories through dance and music. Dances can represent how the character from Hindu scripture fights demons and evil spirits.",
    image: assets.bali_dancer,
    img1: assets.dancer1,
    img2: assets.dancer2,
    trip: [
      {
        id: "1",
        place: "Kuta",
        subplace: "Bali",
        date: "Sep 1-3",
        long: " | 3 days",
        Type: "Business",
        image: assets.nari1,
      },
      {
        id: "2",
        place: "Kuta",
        subplace: "Bali",
        date: "Sep 15-17",
        long: " | 3 days",
        Type: "Business",
        image: assets.nari2,
      },
      {
        id: "3",
        place: "Kuta",
        subplace: "Bali",
        date: "Sep 22-24",
        long: " | 3 days",
        Type: "Business",
        image: assets.nari3,
      },
    ],
  },
  {
    id: "NFT-03",
    name: "Bambang Saputra",
    creator: "Samatiga, Aceh",
    role: 'Fisherman',
    people: assets.nelayan_face,
    price: 95.25,
    description:
      "I am a handline fishing captain on the KM Idola vessel. I am also a hard worker and I have been working for 15 years as a fisherman. My principle of my life is : Whatever we get is the result that God gives today, because God has never changed people’s livelihood.",
    image: assets.nelayan,
    img1: assets.nelayan1,
    img2: assets.nelayan2,
    trip: [
      {
        id: "1",
        place: "Samatiga",
        subplace: "Aceh",
        date: "Sep 1-3",
        long: " | 3 days",
        Type: "Business",
        image: assets.farmer1,
      },
      {
        id: "2",
        place: "Samatiga",
        subplace: "Aceh",
        date: "Sep 15-17",
        long: " | 3 days",
        Type: "Business",
        image: assets.farmer1,
      },
      {
        id: "3",
        place: "Samatiga",
        subplace: "Aceh",
        date: "Sep 22-24",
        long: " | 3 days",
        Type: "Business",
        image: assets.farmer1,
      },
    ],
  },
  {
    id: "NFT-04",
    name: "Andi Nugroho",
    creator: "Danau Teluk, Jambi",
    people: assets.andi,
    role: 'Designer',
    price: 54.25,
    description:
      "Indonesian batik, which is thought to be over 1,000 years old, was added to UNESCO’s Intangible Cultural Heritage of Humanity list in 2009. UNESCO states, “The craft of batik is intertwined with the cultural identity of the Indonesian people and, through the symbolic meanings of its colors and designs, expresses their creativity and spirituality",
    image: assets.batik,
    img1: assets.batik1,
    img2: assets.batik2,
    trip: [
      {
        id: "1",
        place: "Danau Teluk",
        subplace: "Jambi",
        date: "Sep 1-3",
        long: " | 3 days",
        Type: "Business",
        image: assets.farmer1,
      },
      {
        id: "2",
        place: "Danau Teluk",
        subplace: "Jambi",
        date: "Sep 15-17",
        long: " | 3 days",
        Type: "Business",
        image: assets.farmer1,
      },
      {
        id: "3",
        place: "Danau Teluk",
        subplace: "Jambi",
        date: "Sep 22-24",
        long: " | 3 days",
        Type: "Business",
        image: assets.farmer1,
      },
    ],
  },


];

export { NFTData };
